# Generated by Django 6.0.3 on 2026-05-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('code',), 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
