# Generated by Django 6.0.3 on 2026-05-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forex', '0004_alter_currency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('show_advanced_currency_features', models.BooleanField(default=True)),
                ('accounts_preferences', models.JSONField(blank=True, default=dict)),
                ('expenses_preferences', models.JSONField(blank=True, default=dict)),
                ('ledger_preferences', models.JSONField(blank=True, default=dict)),
                ('ui_preferences', models.JSONField(blank=True, default=dict)),
                ('preferred_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferred_by_users', to='forex.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
