# Generated by Django 6.0.3 on 2026-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
