# Generated by Django 6.0.3 on 2026-04-26 17:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expense_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_category_per_user_case_insensitive',
        ),
        migrations.RemoveConstraint(
            model_name='expensetype',
            name='unique_type_per_user_case_insensitive',
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_expensecategory_per_user_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_expensetype_per_user_case_insensitive'),
        ),
    ]
