# Generated by Django 6.0.3 on 2026-05-19 14:31

from django.db import migrations


def populate_defaults(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    ExpenseType = apps.get_model('expenses', 'ExpenseType')

    default_categories = [
        "Food",
        "Transport",
        "Subscriptions",
        "Entertainment",
        "Shopping",
        "Health",
        "Utilities",
        "Lifestyle",
        "Groceries",
    ]

    default_types = [
        'UPI',
        "Credit Card",
        "Debit Card",
        "Cash",
        "Bank Transfer (NEFT/RTGS/IMPS)",
    ]

    for name in default_categories:
        ExpenseCategory.objects.get_or_create(name=name, user=None)

    for name in default_types:
        ExpenseType.objects.get_or_create(name=name, user=None)


def reverse_populate_defaults(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    ExpenseType = apps.get_model('expenses', 'ExpenseType')

    default_categories = [
        "Food",
        "Transport",
        "Subscriptions",
        "Entertainment",
        "Shopping",
        "Health",
        "Utilities",
        "Lifestyle",
        "Groceries",
    ]

    default_types = [
        'UPI',
        "Credit Card",
        "Debit Card",
        "Cash",
        "Bank Transfer (NEFT/RTGS/IMPS)",
    ]

    ExpenseCategory.objects.filter(name__in=default_categories, user__isnull=True).delete()
    ExpenseType.objects.filter(name__in=default_types, user__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0010_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_defaults, reverse_code=reverse_populate_defaults),
    ]