# Generated by Django 6.0.3 on 2026-03-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20260323_1249'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_user_id_51d8ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_categor_20264a_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_type_id_8b5276_idx',
        ),
    ]
