# Generated by Django 6.0.3 on 2026-03-23 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_expense_expenses_ex_user_id_51d8ba_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_date_17a2b2_idx',
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-date'], name='expenses_ex_user_id_4af51e_idx'),
        ),
    ]
