# Generated by Django 6.0.3 on 2026-03-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['name']},
        ),
    ]
