# Generated by Django 6.0.3 on 2026-03-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensetype_remove_expensecategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
