# Generated by Django 6.0.3 on 2026-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
