# Generated by Django 6.0.3 on 2026-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_expenses_ex_date_17a2b2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
