# Generated by Django 6.0.3 on 2026-04-09 12:17

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensecategory_user_expensetype_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['name'], 'verbose_name': 'Expense Type', 'verbose_name_plural': 'Expense Types'},
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_type_per_user_case_insensitive'),
        ),
    ]
