# Generated by Django 6.0.3 on 2026-03-23 12:49

from django.db import migrations


def create_default_data(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    ExpenseType = apps.get_model('expenses', 'ExpenseType')

    categories = [
        "Food",
        "Transport",
        "Bills",
        "Entertainment",
        "Shopping",
        "Health",
    ]

    for name in categories:
        ExpenseCategory.objects.get_or_create(name=name)

    types = [
        "UPI",
        "Credit Card",
        "Debit Card",
        "Cash",
        "Bank Transfer (NEFT/RTGS/IMPS)",
    ]

    for name in types:
        ExpenseType.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_note'),
    ]

    operations = [
        migrations.RunPython(create_default_data, reverse_code=migrations.RunPython.noop),
    ]