# Generated by Django 6.0.3 on 2026-04-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_amount_positive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
