# Generated by Django 6.0.3 on 2026-05-12 19:15

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expense_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_expensecategory_per_user_case_insensitive',
        ),
        migrations.RemoveConstraint(
            model_name='expensetype',
            name='unique_expensetype_per_user_case_insensitive',
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), condition=models.Q(('is_deleted', False)), name='unique_expensecategory_per_user_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), condition=models.Q(('is_deleted', False)), name='unique_expensetype_per_user_case_insensitive'),
        ),
    ]
