# Generated by Django 6.0.3 on 2026-05-27 10:15

from django.db import migrations
from django.db.models import F

from decimal import Decimal

def populate_extra_forex_fields(apps, schema_editor):

    Expense = apps.get_model('expenses', 'Expense')
    Currency = apps.get_model('forex', 'Currency')

    # Historical expenses were stored before multi-currency support
    # was introduced, so all existing amounts are assumed to be INR.
    inr = Currency.objects.get(code='INR').first()

    if not inr:
        return

    Expense._base_manager.filter(currency__isnull=True).update(
        currency=inr,
        exchange_rate=Decimal('1'),
        amount_entered=F('amount'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_seed_currencies'),
        ('expenses', '0012_expense_amount_entered_expense_currency_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_extra_forex_fields, migrations.RunPython.noop),
    ]
