# Generated by Django 6.0.3 on 2026-05-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_fill_extra_forex_fields'),
        ('forex', '0003_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount_entered',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forex.currency'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
    ]
