# Generated by Django 6.0.3 on 2026-05-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_alter_expense_amount_entered_alter_expense_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
    ]
