# Generated by Django 6.0.3 on 2026-08-10 17:48

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_alter_expense_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_expensecategory_per_user_case_insensitive',
        ),
        migrations.RemoveConstraint(
            model_name='expensetype',
            name='unique_expensetype_per_user_case_insensitive',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_ex_is_dele_bb1e13_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.expensetype'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_expensecategory_per_user_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_expensetype_per_user_case_insensitive'),
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='expensetype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='expensetype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_deleted',
        ),
    ]
