# Generated by Django 6.0.3 on 2026-06-26 12:28

from django.db import migrations

def forwards(apps, schema_editor):
    Transaction = apps.get_model("ledger", "Transaction")

    Transaction.objects.filter(type="BORROWED").update(
        type="MONEY_RECEIVED"
    )

    Transaction.objects.filter(type="LENT").update(
        type="MONEY_SENT"
    )

    Transaction.objects.filter(type="PAYMENT_SENT").update(
        type="MONEY_SENT"
    )

    Transaction.objects.filter(type="PAYMENT_RECEIVED").update(
        type="MONEY_RECEIVED"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
