# Generated by Django 6.0.3 on 2026-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_modify_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('MONEY_SENT', 'Money Sent'), ('MONEY_RECEIVED', 'Money Received')], max_length=20),
        ),
    ]
