# Generated by Django 6.0.3 on 2026-07-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='link_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linked_user',
        ),
    ]
