# Generated by Django 6.0.3 on 2026-08-10 17:48

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_contact_link_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_per_user_insensitive',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_deleted',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_contact_per_user_insensitive'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_deleted',
        ),
    ]
