# Generated by Django 6.0.3 on 2026-07-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='unit',
            new_name='default_unit',
        ),
    ]
