# Generated by Django 6.0.3 on 2026-08-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_dailyprogress_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprogress',
            options={'ordering': ['-date', '-id']},
        ),
    ]
