# Generated by Django 6.0.3 on 2026-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_rename_unit_habit_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
