# Generated by Django 6.0.3 on 2026-08-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_dailyprogress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-is_active', 'name']},
        ),
    ]
