# Generated by Django 6.0.3 on 2026-05-18 14:29

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_transaction_date_alter_transaction_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('name', 'user')},
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_contact_per_user_insensitive',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BORROWED', 'Borrowed'), ('LENT', 'Lent'), ('PAYMENT_SENT', 'Payment Sent'), ('PAYMENT_RECEIVED', 'Payment Received')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), condition=models.Q(('is_deleted', False)), name='unique_contact_per_user_insensitive'),
        ),
    ]
