# Generated by Django 6.0.3 on 2026-08-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_contact_unique_contact_per_user_insensitive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
