# Generated by Django 6.0.3 on 2026-08-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_remove_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TransactionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('carry_forward_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward_settlement', to='ledger.transaction')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='ledger.contact')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.transactionsettlement'),
        ),
        migrations.AddConstraint(
            model_name='transactionsettlement',
            constraint=models.UniqueConstraint(fields=('contact', 'date'), name='unique_contact_settlement_per_date'),
        ),
    ]
