# Generated by Django 6.0.3 on 2026-08-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_transaction_is_settled_transactionsettlement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionsettlement',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveConstraint(
            model_name='transactionsettlement',
            name='unique_contact_settlement_per_date',
        ),
        migrations.RemoveField(
            model_name='transactionsettlement',
            name='date',
        ),
    ]
