# Generated by Django 6.0.3 on 2026-08-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_transactionsettlement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Example: Mom, Dad', max_length=100),
        ),
    ]
