# Generated by Django 6.0.3 on 2026-05-30 11:32

from django.db import migrations
from django.conf import settings


def create_user_preference_rows(apps, schema_editor):

    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserPreference = apps.get_model('accounts', 'UserPreference')
    Currency = apps.get_model('forex', 'Currency')

    inr = Currency.objects.get(code='INR')

    UserPreference.objects.bulk_create(
        [
            UserPreference(
                user=user,
                preferred_currency=inr,
            )
            for user in User.objects.all()
        ]
    )



class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_seed_currencies'),
        ('accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.RunPython(
            create_user_preference_rows,
            migrations.RunPython.noop
        ),
    ]
