# Generated by Django 6.0.3 on 2026-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_preference_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='ui_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='habits_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
