# Generated by Django 6.0.3 on 2026-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userpreference_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='accounts_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='expenses_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='habits_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='ledger_preferences',
            field=models.JSONField(default=dict),
        ),
    ]
