# Generated by Django 6.0.3 on 2026-08-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userpreference_accounts_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='show_advanced_currency_features',
        ),
    ]
