# Generated by Django 6.0.3 on 2026-05-19 19:22

from django.db import migrations
from django.conf import settings

import requests
from currency_symbols import CurrencySymbols

def seed_currencies(apps, schema_editor):

    Currency = apps.get_model('forex', 'Currency')

    base_url = getattr(settings, 'EXCHANGE_RATE_BASE_URL', None)
    api_key = getattr(settings, 'EXCHANGE_RATE_API_KEY', None)

    if not (api_key or base_url):
        raise ValueError("EXCHANGE_RATE_API_KEY is missing from settings.")

    url = f"{base_url}/{api_key}/codes"

    response = requests.get(url, timeout=20)
    if response.status_code != 200:
        raise Exception(f"Failed to fetch currencies from API. Status Code: {response.status_code}")

    data = response.json()
    if data['result'] == "error":
        raise Exception(f"Failed to fetch currencies from API. Error Type: {data['error-type']}")

    codes = data.get("supported_codes", [])

    if not codes:
        raise Exception("API returned an empty list of currencies.")

    for code, name in codes:
        symbol = CurrencySymbols.get_symbol(code) or ""

        Currency.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "symbol": symbol,
                "is_active": True
            }
        )

def remove_currencies(apps, schema_editor):
    Currency = apps.get_model('forex', 'Currency')
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_currencies, remove_currencies),
    ]
