# Generated by Django 6.0.3 on 2026-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_seed_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
